---
classes:
  - role::htcondor_worker
  - 'profile::cvmfs'
  - 'profile::arc_env'
  - 'profile::voenv'
  - profile::cgroups

packages_to_install:
  - HEP_OSlibs_SL6
  - cmake
  - gcc-gfortran

htcondor::is_worker: true
htcondor::enable_cgroup: true
